### PR TITLE
Use teams instead of projects to filter stories

### PR DESCRIPTION
**Pull request by hannaholl**

### CODE REVIEW

**Comment by BRMatt** [comment]
@hannaholl so it looks like you should have access to this app in heroku for checking the errors, but it seems like an npm package failed to compile? I don't quite understand why though as it doesn't look like you've changed the dependencies...?

```
-----> Building on the Heroku-20 stack
-----> Using buildpacks:
       1. heroku/nodejs
       2. https://github.com/danp/heroku-buildpack-runit
       3. https://github.com/niteoweb/heroku-buildpack-shell
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 18.x...
       Downloading and installing node 18.12.1...
       Using default npm version: 8.19.2
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.19)
       Installed yarn 1.22.19
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.19
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       $ cd ./client && yarn build
       yarn run v1.22.19
       $ NODE_ENV=production webpack --mode production
       Error: error:0308010C:digital envelope routines::unsupported
           at new Hash (node:internal/crypto/hash:71:19)
           at Object.createHash (node:crypto:133:10)
           at module.exports (/tmp/build_859549fe/node_modules/webpack/lib/util/createHash.js:90:53)
           at NormalModule._initBuildHash (/tmp/build_859549fe/node_modules/webpack/lib/NormalModule.js:401:16)
           at handleParseError (/tmp/build_859549fe/node_modules/webpack/lib/NormalModule.js:449:10)
           at /tmp/build_859549fe/node_modules/webpack/lib/NormalModule.js:481:5
           at /tmp/build_859549fe/node_modules/webpack/lib/NormalModule.js:342:12
           at /tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:373:3
           at iterateNormalLoaders (/tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
           at iterateNormalLoaders (/tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
           at /tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:236:3
           at runSyncOrAsync (/tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
           at iterateNormalLoaders (/tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
           at Array.<anonymous> (/tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
           at Storage.finished (/tmp/build_859549fe/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
           at /tmp/build_859549fe/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
           at /tmp/build_859549fe/node_modules/graceful-fs/graceful-fs.js:90:16
           at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
       node:internal/crypto/hash:71
         this[kHandle] = new _Hash(algorithm, xofLen);
                         ^
       
       Error: error:0308010C:digital envelope routines::unsupported
           at new Hash (node:internal/crypto/hash:71:19)
           at Object.createHash (node:crypto:133:10)
           at module.exports (/tmp/build_859549fe/node_modules/webpack/lib/util/createHash.js:90:53)
           at NormalModule._initBuildHash (/tmp/build_859549fe/node_modules/webpack/lib/NormalModule.js:401:16)
           at handleParseError (/tmp/build_859549fe/node_modules/webpack/lib/NormalModule.js:449:10)
           at /tmp/build_859549fe/node_modules/webpack/lib/NormalModule.js:481:5
           at /tmp/build_859549fe/node_modules/webpack/lib/NormalModule.js:342:12
           at /tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:373:3
           at iterateNormalLoaders (/tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
           at Array.<anonymous> (/tmp/build_859549fe/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
           at Storage.finished (/tmp/build_859549fe/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
           at /tmp/build_859549fe/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
           at /tmp/build_859549fe/node_modules/graceful-fs/graceful-fs.js:90:16
           at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
         opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
         library: 'digital envelope routines',
         reason: 'unsupported',
         code: 'ERR_OSSL_EVP_UNSUPPORTED'
       }
       
       Node.js v18.12.1
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by BRMatt** [comment]
Maybe we need to do this? https://bobbyhadz.com/blog/react-error-digital-envelope-routines-unsupported

**Comment by BRMatt** [comment]
So, I clicked on the `Deploy` tab in heroku, then looked at the logs - it seems it fell over when attempting to run the migrations:

CleanShot 2022-11-11 at 09 47 49@2x

I had [a quick google](https://www.google.com/search?q=heroku+deploy+app+no+pg_hba.conf+entry&rlz=1C5CHFA_enGB961GB961&oq=heroku+deploy+app+no+pg_hba.conf+entry&aqs=chrome..69i57j33i160l2j33i22i29i30.9034j0j7&sourceid=chrome&ie=UTF-8), and found [this help article](https://help.heroku.com/DR0TTWWD/seeing-fatal-no-pg_hba-conf-entry-errors-in-postgres), which seems to imply the issue could be that keeper is not using SSL to connect to its database.

Heroku seem to recommend [this approach](https://help.heroku.com/QD1AIH8R/how-do-i-use-sequelize-to-connect-to-heroku-postgres) to connecting to the database, but I think we configure it in this way as that's how the sequelize docs recommend applying DB migrations:

https://github.com/geckoboard/keeper/blob/fa1608404f2536c086af36c2fe56855ff001d0c8/server/server/config/config.json#L11

Looking at the sequelize docs I think we should be able to combine the "use environment variables" options with the `dialectOptions` that enable SSL. 

https://sequelize.org/docs/v6/other-topics/migrations/#the-sequelizerc-file

**Comment by hannaholl** [comment]
@BRMatt Thanks for looking into it! Any idea why it has worked in the past and is failing now?

**Comment by BRMatt** [comment]
Nope, none!

**Pull request merged**
